eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ACCOUNT-MGT-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQLDialect
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: sa
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"




